import { expect } from 'chai';
import { ethers } from 'hardhat';
// NOTICE HERE: import autogenerated types
import { MockOT, MockOT__factory } from '@typechained';

describe('testing time', function () {
  // NOTICE HERE: we can give our contract a `mockOT` type!! instead of an `any` type.
  let mockOT: MockOT;
  let mockOTFactory: MockOT__factory;

  beforeEach(async () => {
    mockOTFactory = (await ethers.getContractFactory('MockOT')) as MockOT__factory;
    mockOT = await mockOTFactory.deploy(500);
  });

  it('be able to retrieve start date and expiry', async function () {
    await mockOT.deployed();

    // console.log(mockOT.address);

    expect(await mockOT.getStart()).to.be.above(100);

    expect(await mockOT.getExpiry()).to.be.above(100);
  });
});
